# Site settings
title: Valuebai
SEOTitle: Valuebai的博客 | Valuebai blog
header-img: img/bg_common.jpg
email: 520huibo@gmail.com
description: "山山水水又相逢，兜兜转转再缘君"
keyword: "终身学习，人工智能，NLP，机器学习，深度学习"
url: "https://valuebai.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Valuebai/Valuebai.github.io.git" # you code repository



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "专注IT，乐于分享。"
sidebar-avatar: /img/avatar-xs.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
douban_username: valuebai
weibo_username: valuebai
zhihu_username: valuebai
github_username: valuebai
#twitter_username:   qiubaiying
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  




# Plugins
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Baidu Share
bd_share: true                          # whether or not using baidu share


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

## Gitalk
# gitalk:
#   enable: true    #是否开启Gitalk评论
#   clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#   clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#   repo: qiubaiying.github.io    #仓库名称
#   owner: qiubaiying    #github用户名
#   admin: qiubaiying
#   distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Livere
# 暂时用不到，先注释掉
# labili: false                           # whether or not using Livere
# labili_uid: MTAyMC80MjI1Ny8xODgwNA==    # data uid




# 统计
# Analytics settings
# 网站分析，现在支持百度统计和Google Analytics。需要去官方网站注册一下，然后将返回的code贴在下面：

# Baidu Analytics
ba_track_id: 675d4dd59ecc68492b7850259db4b17b

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # 你用Google账号去注册一个就会给你一个这样的id
#ga_domain: https://valuebai.github.io/	  # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto。

# 谷歌地址，需要具体网站，github的无效，https://analytics.google.com/analytics/web/provision/?authuser=0#/provision/create






# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true




# Friends
friends: [
    {
        title: "Valuebai CSDN",
        href: "https://blog.csdn.net/luhuibo318"
    },
    {
        title: "Xs blog",
        href: "http://xiaosheng.me"
    }
]
